osx_image: xcode12.5
language: objective-c
xcode_project: BlockHookSample
xcode_scheme: BlockHook iOS
xcode_sdk: iphoneos14.5
os: osx
env:
  global:
  - FRAMEWORK_NAME=BlockHook
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script:
- xcodebuild -project BlockHookSample.xcodeproj -scheme "BlockHookSample iOS" -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5' ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  token:
    secure: bfE7slv9dJNwMdFodHjjrQkvakQDImBFrg4MnL6NwibcKjnayefsfV4iGy1cHxI0PUPTHs8T3ZPm5987ViLZryg+s9UrtZRtGEtIeLYrcRvPjr3sBSj9jnbS9vWYvuXOiYGkuYHRIwkY4iqA7ULOn0s86HKWWxcYUcUKGv94/JwvWTxH8SCd1LaC42JVazajpF9DdlZzwjcu/4qQCsrfapPVetjO0R4YblERmq8ZZBODUJgV2WAaPdMJeuiE6/90YYdrJ3zbntHRWNqptGOObYSvH2bcXiDPzCSjGi7BQ7r5TP3sjrL8oX6SVvmCFiqqWno2pycAyn6MVkOrmWmYAy/84QVnSJ6hL8RDA/XPoOZFPWiFUyS6+5T1yYbcEcxHwbXF9EUK4CDSiNUMmy3DPX9SlI1PSj8AgF9gbJzQ20Vv2xQ7kq3tQO40pXtoPrP/ve+3drJs3T3WqYcGf33dTy5yd78N25SZY4kensKtd8X+ldjMtAfOURAOqwnaQ/Zqb/sq5frEkrewrj7C4m5ZxwFrejFdywl2Q1ptXY+dF6wj28X3gwjnMuzUyHH38umJ1naRQQpnOU/zcu+hix2u555Wd/5AyylbGXSXClBYR8cxjLSyAL6zL2TGVifW0aGEyNZwf3AGu2QnPxbdNvkVYTK4BAl6pt1pNYMx5+MjQog=
  file: BlockHook.framework.zip
  cleanup: false
  on:
    repo: yulingtianxia/BlockHook
    tags: true
