osx_image: xcode12.5
language: objective-c
xcode_project: crackedauthSample
xcode_scheme: crackedauthiOS
xcode_sdk: iphoneos14.5
os: osx
env:
  global:
  - FRAMEWORK_NAME=crackedauth
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script:
- xcodebuild -project crackedauthSample.xcodeproj -scheme "crackedauthSampleiOS" -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5' ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  token:
    secure: x-x-x-x
  file: crackedauth.framework.zip
  cleanup: false
  on:
    repo: pxcs/crackedauth
    tags: true
